# Generated by Django 3.2.13 on 2023-02-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('w', 'Weekly'), ('M', 'Monthly')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
